<a href="https://colab.research.google.com/github/GerardoMunoz/Vision/blob/main/Intro_TF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro to TensorFlow

## Tensors
A **tensor** is a generalization of matrices to more than two dimensions.




In [1]:
import tensorflow as tf

t = tf.constant([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("Tensor t:\n", t)

Tensor t:
 tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


### Special Cases
* A **scalar** is a tensor of 0 dimensions.  
* A **vector** is a tensor of 1 dimension.  
* A **matrix** is a tensor of 2 dimensions.

### Definitions
* **Shape:** Describes the lengths of all axes.  
* **Size:** The total number of elements in the tensor.  
* **Rank:** The number of axes in the tensor. It is not the rank of linear algebra.  
* **Axis:** Refers to a specific dimension within the tensor.

### Example
Consider the following tensor:  
`t = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])`

* **Shape:** `t.shape` → `(2, 2, 2)`  
* **Size:** `2 × 2 × 2 = 8` elements  
* **Rank:** 3  
* **Axes:**  
  * `axis=0` → the outermost dimension (two 2×2 matrices)  
  * `axis=1` → the rows within each matrix  
  * `axis=2` → the columns within each row

In [2]:

print("Shape:", t.shape)

Shape: (2, 2, 2)


In [3]:
print("Size:", tf.size(t))

Size: tf.Tensor(8, shape=(), dtype=int32)


In [8]:
#t.size
'''error
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipython-input-271257305.py in <cell line: 0>()
----> 1 t.size

/usr/local/lib/python3.12/dist-packages/tensorflow/python/framework/tensor.py in __getattr__(self, name)
    253                 "tolist", "data"}:
    254       # TODO(wangpeng): Export the enable_numpy_behavior knob
--> 255       raise AttributeError(
    256           f"{type(self).__name__} object has no attribute '{name}'. " + """
    257         If you are looking for numpy-related methods, please run the following:

AttributeError: EagerTensor object has no attribute 'size'.
        If you are looking for numpy-related methods, please run the following:
        tf.experimental.numpy.experimental_enable_numpy_behavior(
'''

'error\n---------------------------------------------------------------------------\nAttributeError                            Traceback (most recent call last)\n/tmp/ipython-input-271257305.py in <cell line: 0>()\n----> 1 t.size\n\n/usr/local/lib/python3.12/dist-packages/tensorflow/python/framework/tensor.py in __getattr__(self, name)\n    253                 "tolist", "data"}:\n    254       # TODO(wangpeng): Export the enable_numpy_behavior knob\n--> 255       raise AttributeError(\n    256           f"{type(self).__name__} object has no attribute \'{name}\'. " + """\n    257         If you are looking for numpy-related methods, please run the following:\n\nAttributeError: EagerTensor object has no attribute \'size\'. \n        If you are looking for numpy-related methods, please run the following:\n        tf.experimental.numpy.experimental_enable_numpy_behavior(\n'

In [9]:
print("Rank:", tf.rank(t)) # It is not the rank of linear algebra

Rank: tf.Tensor(3, shape=(), dtype=int32)


In [10]:
# Accessing elements along different axes
print("Axis 0 (outermost):")
print('t[0]=',t[0])  # first 2x2 matrix
print('t[1]=',t[1])  # second 2x2 matrix

Axis 0 (outermost):
t[0]= tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
t[1]= tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


In [11]:
print("Axis 1 (rows within each matrix):")
print('t[:, 0]=',t[:, 0])  # first row from each matrix
print('t[:, 1]=',t[:, 1])  # second row from each matrix

Axis 1 (rows within each matrix):
t[:, 0]= tf.Tensor(
[[1 2]
 [5 6]], shape=(2, 2), dtype=int32)
t[:, 1]= tf.Tensor(
[[3 4]
 [7 8]], shape=(2, 2), dtype=int32)


In [12]:
print("Axis 2 (columns within each row):")
print('t[:, :, 0]=',t[:, :, 0])  # first column from each row
print('t[:, :, 1=',t[:, :, 1])  # second column from each row


Axis 2 (columns within each row):
t[:, :, 0]= tf.Tensor(
[[1 3]
 [5 7]], shape=(2, 2), dtype=int32)
t[:, :, 1= tf.Tensor(
[[2 4]
 [6 8]], shape=(2, 2), dtype=int32)


### More about tensors
* https://www.tensorflow.org/tutorials/customization/basics?hl=es-419

## TensorFlow Playground

* https://playground.tensorflow.org/

##

## CNN
* https://gerardomunoz.github.io/ML_2025/Conv2D.html
* https://youtu.be/eMXuk97NeSI?t=19

## Transposed Convolution
It is used in autoencoders to increase the number of pixels in the image, it is the opposite operation to Pooling
* https://gerardomunoz.github.io/ML_2025/Conv2DTranspose.html

## Example of Neural Networks

* Dense https://colab.research.google.com/github/tensorflow/docs-l10n/blob/master/site/es-419/tutorials/quickstart/beginner.ipynb?hl=es-419

* CNN https://colab.research.google.com/github/tensorflow/docs-l10n/blob/master/site/es-419/tutorials/keras/classification.ipynb?hl=es-419

* Autoencoders https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/generative/autoencoder.ipynb?hl=es-419




##